### ISSUE TITLE
account verification broken

### ISSUE THREAD

**Issue by IQXLEXI** [Yaro2709/New-Star#43]
Hi @Yaro2709 it seems there is an issue with the account verification part, I tried first with sendmail, it failed.
However phpmailer wasn't working either ... I set "way to send email (mail_use)" = 2

Message: sendmail is deprecated, use SMTP instead!
File: /includes/classes/Mail.class.php
Line: 72
URL: http://localhost/uni1/index.php?page=register
PHP-Version: 7.4.3
PHP-API: fpm-fcgi
Version: 2.7.0
Debug Backtrace:
#0 /includes/classes/Mail.class.php(22): Mail::getMailObject()
#1 /includes/pages/login/ShowRegisterPage.class.php(325): Mail::send()
#2 /index.php(57): ShowRegisterPage->send()
#3 {main}

PHPMAILER ERROR

USER ERROR
Message: Class 'SMTP' not found
File: /includes/libs/phpmailer/class.phpmailer.php
Line: 1520
URL: http://localhost/uni1/index.php?page=register
PHP-Version: 7.4.3
PHP-API: fpm-fcgi
Version: 2.7.0
Debug Backtrace:
#0 /includes/libs/phpmailer/class.phpmailer.php(1603): PHPMailer->getSMTPInstance()
#1 /includes/libs/phpmailer/class.phpmailer.php(1540): PHPMailer->smtpConnect()
#2 /includes/libs/phpmailer/class.phpmailer.php(1335): PHPMailer->smtpSend()
#3 /includes/libs/phpmailer/class.phpmailer.php(1213): PHPMailer->postSend()
#4 /includes/classes/Mail.class.php(28): PHPMailer->send()
#5 /includes/pages/login/ShowRegisterPage.class.php(325): Mail::send()
#6 /index.php(57): ShowRegisterPage->send()
#7 {main}

any suggestions on that?

**Comment by sangu71** [comment]
hello thank's a lot for your game ,

it's possible to have a correction for this problem ?

i have this , when i use mail fonction : 


Message: Could not instantiate mail function.
File: /includes/libs/phpmailer/class.phpmailer.php
Line: 1507
URL: http://localhost/index.php?page=lostPassword
PHP-Version: 7.4.26
PHP-API: apache2handler
Version: 2.8.1
Debug Backtrace:
#0 /includes/libs/phpmailer/class.phpmailer.php(1337): PHPMailer->mailSend('Date: Sun, 19 M...', 'Bonjour Empereu...')
#1 /includes/libs/phpmailer/class.phpmailer.php(1213): PHPMailer->postSend()
#2 /includes/classes/Mail.class.php(28): PHPMailer->send()
#3 /includes/pages/login/ShowLostPasswordPage.class.php(196): Mail::send('seb9194@gmail.c...', 'admin', 'Mot de passe ou...', 'Bonjour Empereu...')
#4 /index.php(57): ShowLostPasswordPage->send()
#5 {main} 



thank's again

**Comment by bin9yuz79** [comment]
Aynı hatayı alıyorum.
![Uploading lost-password2.png…]()
