### ISSUE TITLE
Galaxy

### ISSUE THREAD

**Issue by anjasamar** [Yaro2709/New-Star#58]
error on galaxy page like this:

Message: Undefined offset: 16
File: /cache/templates/en_nsc^07f8136c3270b3f5e85ca2d63eeaa7540687dffa.page.galaxy.default.tpl.php
Line: 800
URL: http://wans.loca.lt/game.php?page=galaxy
PHP-Version: 7.4.26
PHP-API: apache2handler
Version: 2.8.1
Debug Backtrace:
#0 /cache/templates/en_nsc^07f8136c3270b3f5e85ca2d63eeaa7540687dffa.page.galaxy.default.tpl.php(800): errorHandler(8, 'Undefined offse...', 'F://wamp64//www//N...', 800, Array)
#1 /includes/libs/Smarty/sysplugins/smarty_template_resource_base.php(123): content_6252eacb90e458_33348290(Object(Smarty_Internal_Template))
#2 /includes/libs/Smarty/sysplugins/smarty_internal_runtime_updatecache.php(52): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /includes/libs/Smarty/sysplugins/smarty_template_cached.php(143): Smarty_Internal_Runtime_UpdateCache->updateCache(Object(Smarty_Template_Cached), Object(Smarty_Internal_Template), false)
#4 /includes/libs/Smarty/sysplugins/smarty_internal_template.php(211): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)
#5 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#6 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#7 /includes/classes/class.template.php(148): Smarty_Internal_TemplateBase->display('extends:layout....')
#8 /includes/pages/game/AbstractGamePage.class.php(505): template->display('extends:layout....')
#9 /includes/pages/game/ShowGalaxyPage.class.php(132): AbstractGamePage->display('page.galaxy.def...')
#10 /game.php(59): ShowGalaxyPage->show()
#11 {main}

**Comment by anjasamar** [comment]
Solution on Admin Panel -> Settings -> Miscellanous -> Planets (max_planet) don't not over (9) on value, and everything is okay :)
