### ISSUE TITLE
error in race page 

### ISSUE THREAD

**Issue by fisher762** [Yaro2709/New-Star#62]
hello there..
i have some errors .. .when i to race page and choose character  i got this

http://localhost/newstar/game.php?page=race
```
Warning: Uncaught ErrorException: require_once(includes/subclasses/subclass.UpdateSqlСhoice.php): failed to open stream: No such file or directory in D:\xampp\htdocs\newstar\includes\pages\game\ShowRacePage.class.php:46 Stack trace: #0 D:\xampp\htdocs\newstar\includes\pages\game\ShowRacePage.class.php(46): errorHandler(2, 'require_once(in...', 'D:\\xampp\\htdocs...', 46, Array) #1 D:\xampp\htdocs\newstar\includes\pages\game\ShowRacePage.class.php(46): require_once() #2 D:\xampp\htdocs\newstar\includes\pages\game\ShowRacePage.class.php(60): ShowRacePage->UpdateRace(1501) #3 D:\xampp\htdocs\newstar\game.php(59): ShowRacePage->show() #4 {main} thrown in D:\xampp\htdocs\newstar\includes\pages\game\ShowRacePage.class.php on line 46

Fatal error: ShowRacePage::UpdateRace(): Failed opening required 'includes/subclasses/subclass.UpdateSqlСhoice.php' (include_path='D:/xampp/htdocs/newstar/') in D:\xampp\htdocs\newstar\includes\pages\game\ShowRacePage.class.php on line 46
```
also this pages
http://localhost/newstar/game.php?page=ethics
http://localhost/newstar/game.php?page=formgovernment

**Comment by 4lin** [comment]
Same for me even online race, form of government and ethics is not working.

**Comment by StevenG916** [comment]
Not sure if this is the problem or not, but once installed and set the system to PHP7.4, i haven't had any problems since

**Comment by Ronneraz** [comment]
this bug is caused by the filename，the file “includes/subclasses/subclass.UpdateSql  [**С**]  hoice.php” is a Russian letter not the english letter。but the code in php are same as the filename。so it can works under the UTF8. you can replace the code in 3 files and rename whe file to make it works in old php visions

**Comment by 4lin** [comment]
the problem was solved i missed one file was not copied on my server (includes/subclasses/subclass.UpdateSqlСhoice.php) that one was missing, so everything works fine on race, ethics and government on php7.4.8
