### ISSUE TITLE
Message: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by jmlechiguero** [Yaro2709/New-Star#64]
Hello, after changing a user to moderator, I get this error, could it be due to the php version?

NOTICE
Message: Trying to access array offset on value of type bool
File: /includes/pages/game/ShowOverviewPage.class.php
Line: 284
URL: http://gt-xnova.260mb.net/game.php
PHP-Version: 7.4.8
PHP-API: apache2handler
Version: 2.8.1
Debug Backtrace:
#0 /includes/pages/game/ShowOverviewPage.class.php(284): errorHandler(8, 'Trying to acces...', 'FILEPATH ...', 284, Array)
#1 /game.php(59): ShowOverviewPage->show()
#2 {main}

If it is not the case, what solution do you have?
From already thank you very much.

**Comment by Yaro2709** [comment]
What were the last actions? Perhaps you have a user without planets.

**Comment by jmlechiguero** [comment]
The last thing I did was create a moderator, check the database, all the planets have users.

**Comment by Yaro2709** [comment]
Make a copy of the database. Create a test server. Go to the database and find the planet that is causing this error. Reset all construction (navy, defense, buildings)

**Comment by jmlechiguero** [comment]
I was deleting planet and user from most modern to old without solving the problem.
I found an error, in the administration panel, in the "Universe" section, it says that there are 56 planets and moons, currently and never exceeded 15, currently they are:
users: 11
planets: 12
moons: 3
Where does the administrator panel get those planets from?
