### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by Lyonbln** [Yaro2709/New-Star#71]
Fatal error: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Language::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/jango-online.de/uni1.jango-online.de/includes/classes/Language.class.php:165 Stack trace: #0 /var/www/vhosts/jango-online.de/uni1.jango-online.de/includes/classes/Language.class.php(18): errorHandler() #1 /var/www/vhosts/jango-online.de/uni1.jango-online.de/includes/common.php(61): require('...') #2 /var/www/vhosts/jango-online.de/uni1.jango-online.de/install/index.php(23): require('...') #3 {main} in /var/www/vhosts/jango-online.de/uni1.jango-online.de/includes/classes/Language.class.php on line 18

**Comment by Zurret** [comment]
Please use an older PHP version (e.g. PHP 7.3) since your current version isn't compatible. You would need to make several adjustments to get it working.

I assume you're using PHP 8.x? Next time, please provide more details and not just the error message.

**Comment by Lyonbln** [comment]
php 7.3 wird ja nicht mehr angeboten, selbst die Version 8.0 ist veraltet.... womit du dir den Kompletten Server verschießt

**Comment by Zurret** [comment]
Das Script ist halt veraltet; eine Alternative wäre, es selbst auf PHP 8.3/8.4 zu aktualisieren. Vielleicht findest du in diesem [Thread](https://2moons.de/index.php?thread/1678-update-new-star-v3-5-0/) hilfe dazu.
